### Create User

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Teste Usuário",    
   "email": "teste@teste.com" ,
   "password": "teste123"
}

### Login

POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email": "teste@teste.com",
	"password": "teste123"
}